name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22  # Adjust if needed
          cache: true  # Enables caching

      - name: Verify go.mod and go.sum
        run: |
          if [ ! -f "go.mod" ]; then
            echo "go.mod not found, initializing module"
            go mod init test-neon
          fi
          if [ ! -f "go.sum" ]; then
            echo "go.sum not found, downloading dependencies"
            go mod tidy
          fi

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
