name: Go App CI/CD

on:
  push:
    branches:
      - master  # Adjust if using a different branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Database Migrations
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}  # Load from GitHub Secrets
        run: go run main.go
